-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 15:48:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HR
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HR` ;

-- -----------------------------------------------------
-- Schema HR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HR` DEFAULT CHARACTER SET utf8 ;
USE `HR` ;

-- -----------------------------------------------------
-- Table `HR`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HR`.`job` ;

CREATE TABLE IF NOT EXISTS `HR`.`job` (
  `JOB_IDENT` CHAR(9) NOT NULL,
  `JOB_TITLE` VARCHAR(45) NULL,
  `MIN_SALARY` DECIMAL(10,2) NULL,
  `MAX_SALARY` DECIMAL(10,2) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`JOB_IDENT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HR`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HR`.`department` ;

CREATE TABLE IF NOT EXISTS `HR`.`department` (
  `DEPT_ID_DEP` CHAR(9) NOT NULL,
  `DEPT_NAME` VARCHAR(15) NULL,
  `MANAGER_ID` CHAR(9) NULL,
  `LOC_ID` CHAR(9) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`DEPT_ID_DEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HR`.`job_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HR`.`job_history` ;

CREATE TABLE IF NOT EXISTS `HR`.`job_history` (
  `EMPL_ID` CHAR(9) NOT NULL,
  `START_DATE` DATE NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `DEPT_ID` CHAR(9) NULL,
  `JOBS_ID` CHAR(9) NULL,
  PRIMARY KEY (`EMPL_ID`),
  INDEX `fk_job_history_job1_idx` (`JOBS_ID` ASC) VISIBLE,
  INDEX `fk_job_history_department1_idx` (`DEPT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_job_history_job1`
    FOREIGN KEY (`JOBS_ID`)
    REFERENCES `HR`.`job` (`JOB_IDENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_history_department1`
    FOREIGN KEY (`DEPT_ID`)
    REFERENCES `HR`.`department` (`DEPT_ID_DEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HR`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HR`.`employee` ;

CREATE TABLE IF NOT EXISTS `HR`.`employee` (
  `EMP_ID` VARCHAR(9) NOT NULL,
  `F_NAME` VARCHAR(45) NULL,
  `L_NAME` VARCHAR(45) NULL,
  `SSN` VARCHAR(9) NULL,
  `B_DATE` DATE NULL,
  `SEX` CHAR(1) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `SALARY` DECIMAL(10,2) NULL,
  `MANAGER_ID` CHAR(9) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `JOB_ID` CHAR(9) NULL,
  `DEP_ID` CHAR(9) NULL,
  PRIMARY KEY (`EMP_ID`),
  INDEX `fk_employee_job1_idx` (`JOB_ID` ASC) VISIBLE,
  INDEX `fk_employee_department1_idx` (`DEP_ID` ASC) VISIBLE,
  CONSTRAINT `fk_employee_job_history`
    FOREIGN KEY (`EMP_ID`)
    REFERENCES `HR`.`job_history` (`EMPL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_job1`
    FOREIGN KEY (`JOB_ID`)
    REFERENCES `HR`.`job` (`JOB_IDENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`DEP_ID`)
    REFERENCES `HR`.`department` (`DEPT_ID_DEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
